%% ========================================================================
%  INTERACTIVE GUI - 3D ROBOTIC ARM SIMULATION
%  ========================================================================
%  Description : Interactive GUI with sliders to control joint angles
%                in real-time and visualize the 3D robotic arm
%  Author      : Sandeep Gupta
%  Platform    : MATLAB R2020a or later
%  ========================================================================

function robotic_arm_gui()
    clc;
    close all;
    
    %% Robot Parameters
    L1 = 1.0;   % Base to Shoulder
    L2 = 0.8;   % Shoulder to Elbow
    L3 = 0.6;   % Elbow to End-Effector
    
    %% Create GUI Figure
    fig = figure('Name', '3D Robotic Arm — Interactive Controller', ...
                 'NumberTitle', 'off', ...
                 'Position', [50 50 1400 800], ...
                 'Color', [0.12 0.12 0.16], ...
                 'MenuBar', 'none', ...
                 'ToolBar', 'figure', ...
                 'Resize', 'on');
    
    %% Create 3D Axes for Robot Visualization
    ax = axes('Parent', fig, ...
              'Position', [0.05 0.15 0.6 0.78], ...
              'Color', [0.15 0.15 0.2]);
    
    %% Control Panel Background
    annotation(fig, 'rectangle', [0.68 0.05 0.3 0.9], ...
               'FaceColor', [0.18 0.18 0.22], ...
               'EdgeColor', [0.3 0.3 0.4], ...
               'LineWidth', 1.5);
    
    %% Title
    uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', '⚙ JOINT CONTROL PANEL', ...
              'Units', 'normalized', ...
              'Position', [0.69 0.88 0.28 0.05], ...
              'BackgroundColor', [0.18 0.18 0.22], ...
              'ForegroundColor', [0.3 0.8 1], ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'HorizontalAlignment', 'center');
    
    %% Slider 1 - Base Rotation (θ1)
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', 'θ₁ — Base Rotation', ...
              'Units', 'normalized', ...
              'Position', [0.69 0.80 0.28 0.04], ...
              'BackgroundColor', [0.18 0.18 0.22], ...
              'ForegroundColor', [0.2 0.6 1], ...
              'FontSize', 11, 'FontWeight', 'bold');
    
    slider1 = uicontrol('Parent', fig, 'Style', 'slider', ...
              'Min', -180, 'Max', 180, 'Value', 45, ...
              'Units', 'normalized', ...
              'Position', [0.69 0.76 0.28 0.03], ...
              'BackgroundColor', [0.25 0.25 0.3]);
    
    label1 = uicontrol('Parent', fig, 'Style', 'text', ...
              'String', '45.0°', ...
              'Units', 'normalized', ...
              'Position', [0.69 0.72 0.28 0.03], ...
              'BackgroundColor', [0.18 0.18 0.22], ...
              'ForegroundColor', 'white', ...
              'FontSize', 11);
    
    %% Slider 2 - Shoulder Rotation (θ2)
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', 'θ₂ — Shoulder Rotation', ...
              'Units', 'normalized', ...
              'Position', [0.69 0.65 0.28 0.04], ...
              'BackgroundColor', [0.18 0.18 0.22], ...
              'ForegroundColor', [0.2 0.9 0.4], ...
              'FontSize', 11, 'FontWeight', 'bold');
    
    slider2 = uicontrol('Parent', fig, 'Style', 'slider', ...
              'Min', -90, 'Max', 90, 'Value', 30, ...
              'Units', 'normalized', ...
              'Position', [0.69 0.61 0.28 0.03], ...
              'BackgroundColor', [0.25 0.25 0.3]);
    
    label2 = uicontrol('Parent', fig, 'Style', 'text', ...
              'String', '30.0°', ...
              'Units', 'normalized', ...
              'Position', [0.69 0.57 0.28 0.03], ...
              'BackgroundColor', [0.18 0.18 0.22], ...
              'ForegroundColor', 'white', ...
              'FontSize', 11);
    
    %% Slider 3 - Elbow Rotation (θ3)
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', 'θ₃ — Elbow Rotation', ...
              'Units', 'normalized', ...
              'Position', [0.69 0.50 0.28 0.04], ...
              'BackgroundColor', [0.18 0.18 0.22], ...
              'ForegroundColor', [1 0.4 0.2], ...
              'FontSize', 11, 'FontWeight', 'bold');
    
    slider3 = uicontrol('Parent', fig, 'Style', 'slider', ...
              'Min', -135, 'Max', 135, 'Value', -45, ...
              'Units', 'normalized', ...
              'Position', [0.69 0.46 0.28 0.03], ...
              'BackgroundColor', [0.25 0.25 0.3]);
    
    label3 = uicontrol('Parent', fig, 'Style', 'text', ...
              'String', '-45.0°', ...
              'Units', 'normalized', ...
              'Position', [0.69 0.42 0.28 0.03], ...
              'BackgroundColor', [0.18 0.18 0.22], ...
              'ForegroundColor', 'white', ...
              'FontSize', 11);
    
    %% End-Effector Position Display
    uicontrol('Parent', fig, 'Style', 'text', ...
              'String', '📍 END-EFFECTOR POSITION', ...
              'Units', 'normalized', ...
              'Position', [0.69 0.33 0.28 0.04], ...
              'BackgroundColor', [0.18 0.18 0.22], ...
              'ForegroundColor', [1 0.6 0.2], ...
              'FontSize', 12, 'FontWeight', 'bold');
    
    pos_label = uicontrol('Parent', fig, 'Style', 'text', ...
              'String', 'X: 0.000  Y: 0.000  Z: 0.000', ...
              'Units', 'normalized', ...
              'Position', [0.69 0.27 0.28 0.05], ...
              'BackgroundColor', [0.22 0.22 0.28], ...
              'ForegroundColor', [0.9 0.9 0.9], ...
              'FontSize', 11, 'FontWeight', 'bold');
    
    %% Reset Button
    uicontrol('Parent', fig, 'Style', 'pushbutton', ...
              'String', '↺ RESET TO HOME', ...
              'Units', 'normalized', ...
              'Position', [0.72 0.15 0.22 0.06], ...
              'BackgroundColor', [0.3 0.5 0.8], ...
              'ForegroundColor', 'white', ...
              'FontSize', 12, 'FontWeight', 'bold', ...
              'Callback', @reset_callback);
    
    %% Random Pose Button
    uicontrol('Parent', fig, 'Style', 'pushbutton', ...
              'String', '🎲 RANDOM POSE', ...
              'Units', 'normalized', ...
              'Position', [0.72 0.08 0.22 0.06], ...
              'BackgroundColor', [0.6 0.3 0.7], ...
              'ForegroundColor', 'white', ...
              'FontSize', 12, 'FontWeight', 'bold', ...
              'Callback', @random_callback);
    
    %% Add Slider Listeners
    addlistener(slider1, 'ContinuousValueChange', @(~,~) update_robot());
    addlistener(slider2, 'ContinuousValueChange', @(~,~) update_robot());
    addlistener(slider3, 'ContinuousValueChange', @(~,~) update_robot());
    
    % Initial plot
    update_robot();
    
    %% ===================== NESTED FUNCTIONS =============================
    
    function update_robot()
        theta1 = get(slider1, 'Value');
        theta2 = get(slider2, 'Value');
        theta3 = get(slider3, 'Value');
        
        % Update labels
        set(label1, 'String', sprintf('%.1f°', theta1));
        set(label2, 'String', sprintf('%.1f°', theta2));
        set(label3, 'String', sprintf('%.1f°', theta3));
        
        % Convert to radians
        t1 = deg2rad(theta1);
        t2 = deg2rad(theta2);
        t3 = deg2rad(theta3);
        
        % Forward Kinematics
        T01 = dh_matrix(t1, L1, 0, pi/2);
        T02 = T01 * dh_matrix(t2, 0, L2, 0);
        T03 = T02 * dh_matrix(t3, 0, L3, 0);
        
        P0 = [0; 0; 0];
        P1 = T01(1:3, 4);
        P2 = T02(1:3, 4);
        P3 = T03(1:3, 4);
        
        % Update position label
        set(pos_label, 'String', sprintf('X: %.3f   Y: %.3f   Z: %.3f', ...
            P3(1), P3(2), P3(3)));
        
        % Clear and redraw
        cla(ax);
        axes(ax);
        
        joints = [P0'; P1'; P2'; P3'];
        
        % Plot links
        plot3(ax, joints(:,1), joints(:,2), joints(:,3), ...
              'Color', [0.1 0.3 0.6], 'LineWidth', 8);
        hold(ax, 'on');
        plot3(ax, joints(:,1), joints(:,2), joints(:,3), ...
              'Color', [0.3 0.7 1], 'LineWidth', 4);
        
        % Plot joints
        colors = [0.2 0.8 0.3; 1 0.8 0; 1 0.4 0.1; 1 0.2 0.3];
        sizes = [120 100 80 60];
        
        for i = 1:4
            scatter3(ax, joints(i,1), joints(i,2), joints(i,3), ...
                     sizes(i), colors(i,:), 'filled', ...
                     'MarkerEdgeColor', 'white', 'LineWidth', 1.5);
        end
        
        % Base platform
        theta_c = linspace(0, 2*pi, 50);
        fill3(ax, 0.15*cos(theta_c), 0.15*sin(theta_c), zeros(1,50), ...
              [0.3 0.3 0.4], 'FaceAlpha', 0.6, 'EdgeColor', [0.5 0.5 0.6]);
        
        % Coordinate frame
        quiver3(ax, 0,0,0, 0.15,0,0, 'r', 'LineWidth', 1.5);
        quiver3(ax, 0,0,0, 0,0.15,0, 'g', 'LineWidth', 1.5);
        quiver3(ax, 0,0,0, 0,0,0.15, 'b', 'LineWidth', 1.5);
        
        hold(ax, 'off');
        
        % Axis formatting
        max_reach = L1 + L2 + L3;
        set(ax, 'Color', [0.15 0.15 0.2], ...
                'XColor', 'w', 'YColor', 'w', 'ZColor', 'w', ...
                'XLim', [-max_reach max_reach], ...
                'YLim', [-max_reach max_reach], ...
                'ZLim', [-0.2 max_reach+0.5]);
        grid(ax, 'on');
        set(ax, 'GridColor', [0.3 0.3 0.4], 'GridAlpha', 0.5);
        xlabel(ax, 'X (m)', 'Color', 'w', 'FontSize', 11);
        ylabel(ax, 'Y (m)', 'Color', 'w', 'FontSize', 11);
        zlabel(ax, 'Z (m)', 'Color', 'w', 'FontSize', 11);
        title(ax, '3D Robotic Arm — Interactive View', ...
              'Color', 'w', 'FontSize', 14, 'FontWeight', 'bold');
        view(ax, 45, 25);
        axis(ax, 'equal');
    end
    
    function reset_callback(~, ~)
        set(slider1, 'Value', 0);
        set(slider2, 'Value', 0);
        set(slider3, 'Value', 0);
        update_robot();
    end
    
    function random_callback(~, ~)
        set(slider1, 'Value', -180 + 360*rand());
        set(slider2, 'Value', -90 + 180*rand());
        set(slider3, 'Value', -135 + 270*rand());
        update_robot();
    end
    
    function T = dh_matrix(theta, d, a, alpha)
        T = [cos(theta), -sin(theta)*cos(alpha),  sin(theta)*sin(alpha), a*cos(theta);
             sin(theta),  cos(theta)*cos(alpha), -cos(theta)*sin(alpha), a*sin(theta);
             0,           sin(alpha),             cos(alpha),            d;
             0,           0,                      0,                     1];
    end
end
